# Generated by Django 5.2.12 on 2026-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fossil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fossilrepository",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fossilrepository",
            name="remote_url",
            field=models.URLField(blank=True, default="", help_text="Upstream remote URL for sync"),
        ),
        migrations.AddField(
            model_name="fossilrepository",
            name="upstream_artifacts_available",
            field=models.PositiveIntegerField(default=0, help_text="New artifacts available from upstream"),
        ),
        migrations.AddField(
            model_name="historicalfossilrepository",
            name="last_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfossilrepository",
            name="remote_url",
            field=models.URLField(blank=True, default="", help_text="Upstream remote URL for sync"),
        ),
        migrations.AddField(
            model_name="historicalfossilrepository",
            name="upstream_artifacts_available",
            field=models.PositiveIntegerField(default=0, help_text="New artifacts available from upstream"),
        ),
    ]
