# Generated by Django 5.2.12 on 2026-04-07 02:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fossil", "0002_fossilrepository_last_sync_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitMirror",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "git_remote_url",
                    models.CharField(help_text="Git remote URL (SSH or HTTPS)", max_length=500),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("ssh", "SSH Key"),
                            ("token", "Personal Access Token"),
                            ("oauth_github", "GitHub OAuth"),
                            ("oauth_gitlab", "GitLab OAuth"),
                        ],
                        default="token",
                        max_length=20,
                    ),
                ),
                (
                    "auth_credential",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted token or key reference",
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("push", "Push (Fossil → Git)"),
                            ("pull", "Pull (Git → Fossil)"),
                            ("both", "Bidirectional"),
                        ],
                        default="push",
                        max_length=10,
                    ),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("on_change", "On Change"),
                            ("scheduled", "Scheduled"),
                            ("both", "Both"),
                            ("disabled", "Disabled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(
                        blank=True,
                        default="*/15 * * * *",
                        help_text="Cron expression for scheduled sync",
                        max_length=100,
                    ),
                ),
                ("sync_code", models.BooleanField(default=True)),
                (
                    "sync_tickets",
                    models.BooleanField(default=False, help_text="Sync tickets as GitHub/GitLab Issues"),
                ),
                (
                    "sync_wiki",
                    models.BooleanField(default=False, help_text="Sync wiki pages"),
                ),
                (
                    "fossil_branch",
                    models.CharField(
                        default="trunk",
                        help_text="Fossil branch to sync",
                        max_length=100,
                    ),
                ),
                (
                    "git_branch",
                    models.CharField(
                        default="main",
                        help_text="Git branch to push to",
                        max_length=100,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("last_sync_message", models.TextField(blank=True, default="")),
                ("total_syncs", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_mirrors",
                        to="fossil.fossilrepository",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalGitMirror",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "git_remote_url",
                    models.CharField(help_text="Git remote URL (SSH or HTTPS)", max_length=500),
                ),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("ssh", "SSH Key"),
                            ("token", "Personal Access Token"),
                            ("oauth_github", "GitHub OAuth"),
                            ("oauth_gitlab", "GitLab OAuth"),
                        ],
                        default="token",
                        max_length=20,
                    ),
                ),
                (
                    "auth_credential",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Encrypted token or key reference",
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("push", "Push (Fossil → Git)"),
                            ("pull", "Pull (Git → Fossil)"),
                            ("both", "Bidirectional"),
                        ],
                        default="push",
                        max_length=10,
                    ),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("on_change", "On Change"),
                            ("scheduled", "Scheduled"),
                            ("both", "Both"),
                            ("disabled", "Disabled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "sync_schedule",
                    models.CharField(
                        blank=True,
                        default="*/15 * * * *",
                        help_text="Cron expression for scheduled sync",
                        max_length=100,
                    ),
                ),
                ("sync_code", models.BooleanField(default=True)),
                (
                    "sync_tickets",
                    models.BooleanField(default=False, help_text="Sync tickets as GitHub/GitLab Issues"),
                ),
                (
                    "sync_wiki",
                    models.BooleanField(default=False, help_text="Sync wiki pages"),
                ),
                (
                    "fossil_branch",
                    models.CharField(
                        default="trunk",
                        help_text="Fossil branch to sync",
                        max_length=100,
                    ),
                ),
                (
                    "git_branch",
                    models.CharField(
                        default="main",
                        help_text="Git branch to push to",
                        max_length=100,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("last_sync_message", models.TextField(blank=True, default="")),
                ("total_syncs", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="fossil.fossilrepository",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical git mirror",
                "verbose_name_plural": "historical git mirrors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSSHKey",
            fields=[
                (
                    "id",
                    models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("public_key", models.TextField()),
                (
                    "private_key_path",
                    models.CharField(help_text="Path to private key file on disk", max_length=500),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ssh key",
                "verbose_name_plural": "historical ssh keys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("public_key", models.TextField()),
                (
                    "private_key_path",
                    models.CharField(help_text="Path to private key file on disk", max_length=500),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("artifacts_synced", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("triggered_by", models.CharField(default="manual", max_length=20)),
                (
                    "mirror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="fossil.gitmirror",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
