# Generated by Django 5.2.12 on 2026-04-07 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fossil", "0011_codereview_historicalcodereview_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticketclaim",
            unique_together=set(),
        ),
    ]
