# Generated by Django 5.2.12 on 2026-04-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fossil", "0012_alter_ticketclaim_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSyncMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fossil_ticket_uuid", models.CharField(max_length=64)),
                ("github_issue_number", models.PositiveIntegerField()),
                (
                    "fossil_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "mirror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_mappings",
                        to="fossil.gitmirror",
                    ),
                ),
            ],
            options={
                "unique_together": {("mirror", "fossil_ticket_uuid")},
            },
        ),
        migrations.CreateModel(
            name="WikiSyncMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fossil_page_name", models.CharField(max_length=500)),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "github_path",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "mirror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wiki_mappings",
                        to="fossil.gitmirror",
                    ),
                ),
            ],
            options={
                "unique_together": {("mirror", "fossil_page_name")},
            },
        ),
    ]
