# Generated by Django 5.2.12 on 2026-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalitem",
            name="sku",
            field=models.CharField(blank=True, db_index=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
